### PR TITLE
Fix order in ***NetworkConnection destructors to avoid crashing client

### LINKED ISSUE #11: Client: Change from game state to menu state crashes
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               game_client [14439]
Path:                  /Users/USER/*/game_client
Identifier:            game_client
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        bash [962]
Responsible:           Terminal [84094]
User ID:               502

Date/Time:             2023-07-04 23:08:35.1564 +0200
OS Version:            macOS 12.6.7 (21G651)
Report Version:        12
Anonymous UUID:        AD7D8DD9-C9A5-62B4-14FD-E77444CC6180

Sleep/Wake UUID:       4B50D85F-E888-4E59-B6C5-44832163097B

Time Awake Since Boot: 300000 seconds
Time Since Wake:       9639 seconds

System Integrity Protection: enabled

Crashed Thread:        12

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called


Thread 0::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff896c72940 ???
1   libsystem_kernel.dylib        	    0x7ff80679a0da __ulock_wait + 10
2   libsystem_pthread.dylib       	    0x7ff8067d6c95 _pthread_join + 358
3   libc++.1.dylib                	    0x7ff80673da06 std::__1::thread::join() + 24
4   game_client                   	       0x10018b57b ClientNetworkConnection::~ClientNetworkConnection() + 1259
5   game_client                   	       0x10019c3da ServerConnection::~ServerConnection() + 410
6   game_client                   	       0x10020e2de jt::GameObjectCollection::clear() + 78
7   game_client                   	       0x10020ed0e jt::GameState::~GameState() + 46
8   game_client                   	       0x100225b59 jt::StateManager::doSwitchState(std::__1::weak_ptr<jt::GameInterface>) + 281
9   game_client                   	       0x100225cbe jt::StateManager::update(std::__1::weak_ptr<jt::GameInterface>, float) + 190
10  game_client                   	       0x1002247fd jt::LoggingStateManager::update(std::__1::weak_ptr<jt::GameInterface>, float) + 397
11  game_client                   	       0x10020d0bf jt::GameBase::doUpdate(float) + 367
12  game_client                   	       0x10020c8e8 jt::GameBase::runOneFrame() + 520
13  game_client                   	       0x1001eb8c3 jt::Game::startGame(void (*)()) + 355
14  game_client                   	       0x100189aa8 main + 2296
15  dyld                          	       0x200adb52e start + 462

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffd76944 0x7ff7ffd72000 + 18756
1   runtime                       	    0x7ff7ffd843e0 0x7ff7ffd72000 + 74720
2   runtime                       	    0x7ff7ffd85e58 0x7ff7ffd72000 + 81496

Thread 2:
0   runtime                       	    0x7ff7ffd94814 0x7ff7ffd72000 + 141332

Thread 3:
0   runtime                       	    0x7ff7ffd94814 0x7ff7ffd72000 + 141332

Thread 4:: AMCP Logging Spool
0   ???                           	    0x7ff896c72940 ???
1   libsystem_kernel.dylib        	    0x7ff8067989a6 semaphore_wait_trap + 10
2   caulk                         	    0x7ff80f7472e6 caulk::mach::semaphore::wait_or_error() + 16
3   caulk                         	    0x7ff80f72f148 caulk::concurrent::details::worker_thread::run() + 36
4   caulk                         	    0x7ff80f72ee0c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 41
5   libsystem_pthread.dylib       	    0x7ff8067d54e1 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff8067d0f6b thread_start + 15

Thread 5:: com.apple.audio.IOThread.client
0   ???                           	    0x7ff896c72940 ???
1   libsystem_kernel.dylib        	    0x7ff80679896a mach_msg_trap + 10
2   libsystem_kernel.dylib        	    0x7ff806798cd8 mach_msg + 56
3   CoreAudio                     	    0x7ff808356c07 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 111
4   CoreAudio                     	    0x7ff8081e1729 HALC_ProxyIOContext::IOWorkLoop() + 3931
5   CoreAudio                     	    0x7ff8081e0205 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 63
6   CoreAudio                     	    0x7ff8083ac616 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	    0x7ff8067d54e1 _pthread_start + 125
8   libsystem_pthread.dylib       	    0x7ff8067d0f6b thread_start + 15

Thread 6:
0   ???                           	    0x7ff896c72940 ???
1   libsystem_kernel.dylib        	    0x7ff8067989a6 semaphore_wait_trap + 10
2   libdispatch.dylib             	    0x7ff80661e7ce _dispatch_sema4_wait + 16
3   libdispatch.dylib             	    0x7ff80661ec9d _dispatch_semaphore_wait_slow + 98
4   game_client                   	       0x10025a9bc EventThread(ALCcontext*) + 956
5   game_client                   	       0x10025ae7c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, int (*)(ALCcontext*), ALCcontext*> >(void*) + 44
6   libsystem_pthread.dylib       	    0x7ff8067d54e1 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff8067d0f6b thread_start + 15

Thread 7:
0   runtime                       	    0x7ff7ffd94814 0x7ff7ffd72000 + 141332

Thread 8:
0   runtime                       	    0x7ff7ffd94814 0x7ff7ffd72000 + 141332

Thread 9:
0   runtime                       	    0x7ff7ffd94814 0x7ff7ffd72000 + 141332

Thread 10:: com.apple.NSEventThread
0   ???                           	    0x7ff896c72940 ???
1   libsystem_kernel.dylib        	    0x7ff80679896a mach_msg_trap + 10
2   libsystem_kernel.dylib        	    0x7ff806798cd8 mach_msg + 56
3   CoreFoundation                	    0x7ff80689f510 __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	    0x7ff80689dba0 __CFRunLoopRun + 1276
5   CoreFoundation                	    0x7ff80689cfe4 CFRunLoopRunSpecific + 562
6   AppKit                        	    0x7ff80937c98e _NSEventThread + 132
7   libsystem_pthread.dylib       	    0x7ff8067d54e1 _pthread_start + 125
8   libsystem_pthread.dylib       	    0x7ff8067d0f6b thread_start + 15

Thread 11:
0   runtime                       	    0x7ff7ffd94814 0x7ff7ffd72000 + 141332

Thread 12 Crashed:
0   ???                           	    0x7ff896c72940 ???
1   libsystem_kernel.dylib        	    0x7ff80679effe __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff8067d51ff pthread_kill + 263
3   libsystem_c.dylib             	    0x7ff806720d24 abort + 123
4   libc++abi.dylib               	    0x7ff806791082 abort_message + 241
5   libc++abi.dylib               	    0x7ff806782245 demangling_terminate_handler() + 242
6   libobjc.A.dylib               	    0x7ff80667f016 _objc_terminate() + 104
7   libc++abi.dylib               	    0x7ff8067904a7 std::__terminate(void (*)()) + 8
8   libc++abi.dylib               	    0x7ff806792d05 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
9   libc++abi.dylib               	    0x7ff806792ccc __cxa_throw + 116
10  game_client                   	       0x1004ca464 asio::detail::do_throw_error(std::__1::error_code const&, char const*) + 100
11  game_client                   	       0x1001e38ac NetworkHelpers::freeHandleReceive(std::__1::error_code const&, unsigned long, asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>&, ReceiveBuffer&, jt::LoggerInterface&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) + 1276
12  game_client                   	       0x10018d0fc asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>, asio::mutable_buffer, asio::mutable_buffer const*, asio::detail::transfer_all_t, ClientNetworkConnection::awaitNextMessage()::$_2>::operator()(std::__1::error_code, unsigned long, int) + 156
13  game_client                   	       0x10018d645 asio::detail::reactive_socket_recv_op<asio::mutable_buffer, asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>, asio::mutable_buffer, asio::mutable_buffer const*, asio::detail::transfer_all_t, ClientNetworkConnection::awaitNextMessage()::$_2>, asio::any_io_executor>::do_complete(void*, asio::detail::scheduler_operation*, std::__1::error_code const&, unsigned long) + 325
14  game_client                   	       0x1004bfe86 asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::__1::error_code const&) + 694
15  game_client                   	       0x1004b49b1 asio::detail::scheduler::run(std::__1::error_code&) + 257
16  game_client                   	       0x1004b482b asio::io_context::run() + 43
17  game_client                   	       0x100190771 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ClientNetworkConnection::startProcessing()::$_0> >(void*) + 65
18  libsystem_pthread.dylib       	    0x7ff8067d54e1 _pthread_start + 125
19  libsystem_pthread.dylib       	    0x7ff8067d0f6b thread_start + 15


Thread 12 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007ff847f14990  rsi: 0x0000000000000003  rbp: 0x00007ff806793f72  rsp: 0x00000003052ca250
   r8: 0x00000003052cb000   r9: 0x00007ff806793f72  r10: 0x0000000000000000  r11: 0x00007ff847ef0290
  r12: 0x000000000001720b  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0xffffffffffffffff tmp1: 0x00007ff896c72914 tmp2: 0x00007ff80679eff4


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff806797000 -     0x7ff8067cefff libsystem_kernel.dylib (*) <d0b338e0-26be-371b-a819-80b7d619a4ad> /usr/lib/system/libsystem_kernel.dylib
    0x7ff8067cf000 -     0x7ff8067dafff libsystem_pthread.dylib (*) <e5d44afd-2577-3cee-8711-9d8d426229e0> /usr/lib/system/libsystem_pthread.dylib
    0x7ff806728000 -     0x7ff806780fff libc++.1.dylib (*) <a031469a-a9fe-37e0-8523-4f80351ea635> /usr/lib/libc++.1.dylib
       0x100181000 -        0x1005e0fff game_client (*) <cbe974ac-0e2f-3397-be30-b56f7cb7d629> /Users/USER/*/game_client
       0x200ad6000 -        0x200b41fff dyld (*) <2517e9fe-884a-3855-8532-92bffba3f81c> /usr/lib/dyld
    0x7ff7ffd72000 -     0x7ff7ffda1fff runtime (*) <fb3e328e-494d-31b1-8832-273afa9336f3> /usr/libexec/rosetta/runtime
    0x7ff80f72d000 -     0x7ff80f74efff com.apple.audio.caulk (1.0) <8e7b3d95-1d47-3f17-9512-c5fcc30792c2> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7ff808027000 -     0x7ff80875cfff com.apple.audio.CoreAudio (5.0) <9be547d0-0af1-3470-afde-2ac4cd34441e> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7ff80661b000 -     0x7ff806661fff libdispatch.dylib (*) <1a04b380-76e4-3e4b-b0fc-9837533d021d> /usr/lib/system/libdispatch.dylib
    0x7ff80681c000 -     0x7ff806d20fff com.apple.CoreFoundation (6.9) <5e33664d-9c9a-3ac4-ad94-641d53e06c7b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff8091d0000 -     0x7ff80a05ffff com.apple.AppKit (6.9) <1a1a9da7-da66-31da-92cd-51b9cf968145> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff80669f000 -     0x7ff806727fff libsystem_c.dylib (*) <e42e9d7a-03b4-340b-b61e-dcd45fd4acc0> /usr/lib/system/libsystem_c.dylib
    0x7ff806781000 -     0x7ff806796fff libc++abi.dylib (*) <a99f1fb2-fd31-3cf4-be4d-a9fccf219974> /usr/lib/libc++abi.dylib
    0x7ff806662000 -     0x7ff80669bfff libobjc.A.dylib (*) <e633b9d0-7686-31f6-92b1-451e39bcf653> /usr/lib/libobjc.A.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=929.8M resident=0K(0%) swapped_out_or_unallocated=929.8M(100%)
Writable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 8704K        8 
CG image                            48K        6 
ColorSync                          220K       25 
CoreAnimation                      112K        8 
CoreGraphics                         8K        2 
CoreServices                       320K        2 
CoreUI image data                 1160K        8 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           706.9M       77 
MALLOC guard page                  192K        8 
MALLOC_MEDIUM (reserved)         824.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           128.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                    792K      195 
Rosetta IndirectBranch             512K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               240K       24 
Rosetta Thread Context             240K       24 
STACK GUARD                         24K        6 
Stack                             13.6M       12 
Stack Guard                       56.0M        6 
VM_ALLOCATE                       5512K       34 
VM_ALLOCATE (reserved)              36K        2         reserved VM address space (unallocated)
__CTF                               756        1 
__DATA                            17.9M      299 
__DATA_CONST                      12.4M      179 
__DATA_DIRTY                       544K       99 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       706.1M       17 
__OBJC_RO                         82.8M        1 
__OBJC_RW                         3200K        2 
__TEXT                           223.8M      317 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                        5.2G      412 
shared memory                      820K       17 
unshared pmap                     8512K        5 
===========                     =======  ======= 
TOTAL                              8.1G     1819 
TOTAL, minus reserved VM space     7.2G     1819 



-----------
Full Report
-----------

{"app_name":"game_client","timestamp":"2023-07-04 23:08:35.00 +0200","app_version":"","slice_uuid":"cbe974ac-0e2f-3397-be30-b56f7cb7d629","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.6.7 (21G651)","incident_id":"625CADED-5BA3-48B5-9444-709E3DA341E6","name":"game_client"}
{
  "uptime" : 300000,
  "procLaunch" : "2023-07-04 22:58:16.4955 +0200",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 7348386860522,
  "coalitionID" : 11904,
  "osVersion" : {
    "train" : "macOS 12.6.7",
    "build" : "21G651",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-04 23:08:35.1564 +0200",
  "incident" : "625CADED-5BA3-48B5-9444-709E3DA341E6",
  "bug_type" : "309",
  "pid" : 14439,
  "procExitAbsTime" : 7363234363777,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "game_client",
  "procPath" : "\/Users\/USER\/*\/game_client",
  "parentProc" : "bash",
  "parentPid" : 962,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "AD7D8DD9-C9A5-62B4-14FD-E77444CC6180",
  "responsiblePid" : 84094,
  "responsibleProc" : "Terminal",
  "wakeTime" : 9639,
  "sleepWakeUUID" : "4B50D85F-E888-4E59-B6C5-44832163097B",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 12,
  "threads" : [{"id":6999188,"queue":"com.apple.main-thread","frames":[{"imageOffset":140705658251584,"imageIndex":0},{"imageOffset":12506,"symbol":"__ulock_wait","symbolLocation":10,"imageIndex":1},{"imageOffset":31893,"symbol":"_pthread_join","symbolLocation":358,"imageIndex":2},{"imageOffset":88582,"symbol":"std::__1::thread::join()","symbolLocation":24,"imageIndex":3},{"imageOffset":42363,"symbol":"ClientNetworkConnection::~ClientNetworkConnection()","symbolLocation":1259,"imageIndex":4},{"imageOffset":111578,"symbol":"ServerConnection::~ServerConnection()","symbolLocation":410,"imageIndex":4},{"imageOffset":578270,"symbol":"jt::GameObjectCollection::clear()","symbolLocation":78,"imageIndex":4},{"imageOffset":580878,"symbol":"jt::GameState::~GameState()","symbolLocation":46,"imageIndex":4},{"imageOffset":674649,"symbol":"jt::StateManager::doSwitchState(std::__1::weak_ptr<jt::GameInterface>)","symbolLocation":281,"imageIndex":4},{"imageOffset":675006,"symbol":"jt::StateManager::update(std::__1::weak_ptr<jt::GameInterface>, float)","symbolLocation":190,"imageIndex":4},{"imageOffset":669693,"symbol":"jt::LoggingStateManager::update(std::__1::weak_ptr<jt::GameInterface>, float)","symbolLocation":397,"imageIndex":4},{"imageOffset":573631,"symbol":"jt::GameBase::doUpdate(float)","symbolLocation":367,"imageIndex":4},{"imageOffset":571624,"symbol":"jt::GameBase::runOneFrame()","symbolLocation":520,"imageIndex":4},{"imageOffset":436419,"symbol":"jt::Game::startGame(void (*)())","symbolLocation":355,"imageIndex":4},{"imageOffset":35496,"symbol":"main","symbolLocation":2296,"imageIndex":4},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":5}]},{"id":6999191,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18756,"imageIndex":6},{"imageOffset":74720,"imageIndex":6},{"imageOffset":81496,"imageIndex":6}]},{"id":6999194,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":6999203,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":6999238,"name":"AMCP Logging Spool","frames":[{"imageOffset":140705658251584,"imageIndex":0},{"imageOffset":6566,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":107238,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":16,"imageIndex":7},{"imageOffset":8520,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":7},{"imageOffset":7692,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":41,"imageIndex":7},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":2},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":2}]},{"id":6999269,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":140705658251584,"imageIndex":0},{"imageOffset":6506,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":7384,"symbol":"mach_msg","symbolLocation":56,"imageIndex":1},{"imageOffset":3341319,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":111,"imageIndex":8},{"imageOffset":1812265,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3931,"imageIndex":8},{"imageOffset":1806853,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":63,"imageIndex":8},{"imageOffset":3692054,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":72,"imageIndex":8},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":2},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":2}]},{"id":6999294,"frames":[{"imageOffset":140705658251584,"imageIndex":0},{"imageOffset":6566,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":14286,"symbol":"_dispatch_sema4_wait","symbolLocation":16,"imageIndex":9},{"imageOffset":15517,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":98,"imageIndex":9},{"imageOffset":891324,"symbol":"EventThread(ALCcontext*)","symbolLocation":956,"imageIndex":4},{"imageOffset":892540,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, int (*)(ALCcontext*), ALCcontext*> >(void*)","symbolLocation":44,"imageIndex":4},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":2},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":2}]},{"id":6999298,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":6999299,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":6999300,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":6999303,"name":"com.apple.NSEventThread","frames":[{"imageOffset":140705658251584,"imageIndex":0},{"imageOffset":6506,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":7384,"symbol":"mach_msg","symbolLocation":56,"imageIndex":1},{"imageOffset":537872,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":10},{"imageOffset":531360,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":10},{"imageOffset":528356,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":10},{"imageOffset":1755534,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":11},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":2},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":2}]},{"id":6999306,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"triggered":true,"id":7003853,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":140703237226354},"r12":{"value":94731},"rosetta":{"tmp2":{"value":140703237271540},"tmp1":{"value":140705658251540},"tmp0":{"value":18446744073709551615}},"rbx":{"value":0},"r8":{"value":12971716608},"r15":{"value":22},"r10":{"value":0},"rdx":{"value":0},"rdi":{"value":140704335612304,"symbolLocation":0,"symbol":"__stderrp"},"r9":{"value":140703237226354},"r13":{"value":206158430216},"rflags":{"value":643},"rax":{"value":0},"rsp":{"value":12971713104},"r11":{"value":140704335463056,"symbolLocation":448,"symbol":"__sFX"},"rcx":{"value":0},"r14":{"value":6},"rsi":{"value":3}},"frames":[{"imageOffset":140705658251584,"imageIndex":0},{"imageOffset":32766,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":1},{"imageOffset":25087,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":2},{"imageOffset":531748,"symbol":"abort","symbolLocation":123,"imageIndex":12},{"imageOffset":65666,"symbol":"abort_message","symbolLocation":241,"imageIndex":13},{"imageOffset":4677,"symbol":"demangling_terminate_handler()","symbolLocation":242,"imageIndex":13},{"imageOffset":118806,"symbol":"_objc_terminate()","symbolLocation":104,"imageIndex":14},{"imageOffset":62631,"symbol":"std::__terminate(void (*)())","symbolLocation":8,"imageIndex":13},{"imageOffset":72965,"symbol":"__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)","symbolLocation":27,"imageIndex":13},{"imageOffset":72908,"symbol":"__cxa_throw","symbolLocation":116,"imageIndex":13},{"imageOffset":3445860,"symbol":"asio::detail::do_throw_error(std::__1::error_code const&, char const*)","symbolLocation":100,"imageIndex":4},{"imageOffset":403628,"symbol":"NetworkHelpers::freeHandleReceive(std::__1::error_code const&, unsigned long, asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>&, ReceiveBuffer&, jt::LoggerInterface&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)","symbolLocation":1276,"imageIndex":4},{"imageOffset":49404,"symbol":"asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>, asio::mutable_buffer, asio::mutable_buffer const*, asio::detail::transfer_all_t, ClientNetworkConnection::awaitNextMessage()::$_2>::operator()(std::__1::error_code, unsigned long, int)","symbolLocation":156,"imageIndex":4},{"imageOffset":50757,"symbol":"asio::detail::reactive_socket_recv_op<asio::mutable_buffer, asio::detail::read_op<asio::basic_stream_socket<asio::ip::tcp, asio::any_io_executor>, asio::mutable_buffer, asio::mutable_buffer const*, asio::detail::transfer_all_t, ClientNetworkConnection::awaitNextMessage()::$_2>, asio::any_io_executor>::do_complete(void*, asio::detail::scheduler_operation*, std::__1::error_code const&, unsigned long)","symbolLocation":325,"imageIndex":4},{"imageOffset":3403398,"symbol":"asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::__1::error_code const&)","symbolLocation":694,"imageIndex":4},{"imageOffset":3357105,"symbol":"asio::detail::scheduler::run(std::__1::error_code&)","symbolLocation":257,"imageIndex":4},{"imageOffset":3356715,"symbol":"asio::io_context::run()","symbolLocation":43,"imageIndex":4},{"imageOffset":63345,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ClientNetworkConnection::startProcessing()::$_0> >(void*)","symbolLocation":65,"imageIndex":4},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":2},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703237238784,
    "size" : 229376,
    "uuid" : "d0b338e0-26be-371b-a819-80b7d619a4ad",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703237468160,
    "size" : 49152,
    "uuid" : "e5d44afd-2577-3cee-8711-9d8d426229e0",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703236784128,
    "size" : 364544,
    "uuid" : "a031469a-a9fe-37e0-8523-4f80351ea635",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4296544256,
    "size" : 4587520,
    "uuid" : "cbe974ac-0e2f-3397-be30-b56f7cb7d629",
    "path" : "\/Users\/USER\/*\/game_client",
    "name" : "game_client"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8601296896,
    "size" : 442368,
    "uuid" : "2517e9fe-884a-3855-8532-92bffba3f81c",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703125938176,
    "size" : 196608,
    "uuid" : "fb3e328e-494d-31b1-8832-273afa9336f3",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703387799552,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 139264,
    "uuid" : "8e7b3d95-1d47-3f17-9512-c5fcc30792c2",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703262994432,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7561216,
    "uuid" : "9be547d0-0af1-3470-afde-2ac4cd34441e",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703235682304,
    "size" : 290816,
    "uuid" : "1a04b380-76e4-3e4b-b0fc-9837533d021d",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703237783552,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5263360,
    "uuid" : "5e33664d-9c9a-3ac4-ad94-641d53e06c7b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703281512448,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15269888,
    "uuid" : "1a1a9da7-da66-31da-92cd-51b9cf968145",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703236222976,
    "size" : 561152,
    "uuid" : "e42e9d7a-03b4-340b-b61e-dcd45fd4acc0",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703237148672,
    "size" : 90112,
    "uuid" : "a99f1fb2-fd31-3cf4-be4d-a9fccf219974",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703235973120,
    "size" : 237568,
    "uuid" : "e633b9d0-7686-31f6-92b1-451e39bcf653",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703234211840,
  "size" : 19331678208,
  "uuid" : "15be71d8-a3e4-3f47-89c9-0c1956dd8c7d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=929.8M resident=0K(0%) swapped_out_or_unallocated=929.8M(100%)\nWritable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 8704K        8 \nCG image                            48K        6 \nColorSync                          220K       25 \nCoreAnimation                      112K        8 \nCoreGraphics                         8K        2 \nCoreServices                       320K        2 \nCoreUI image data                 1160K        8 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           706.9M       77 \nMALLOC guard page                  192K        8 \nMALLOC_MEDIUM (reserved)         824.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           128.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                    792K      195 \nRosetta IndirectBranch             512K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               240K       24 \nRosetta Thread Context             240K       24 \nSTACK GUARD                         24K        6 \nStack                             13.6M       12 \nStack Guard                       56.0M        6 \nVM_ALLOCATE                       5512K       34 \nVM_ALLOCATE (reserved)              36K        2         reserved VM address space (unallocated)\n__CTF                               756        1 \n__DATA                            17.9M      299 \n__DATA_CONST                      12.4M      179 \n__DATA_DIRTY                       544K       99 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       706.1M       17 \n__OBJC_RO                         82.8M        1 \n__OBJC_RW                         3200K        2 \n__TEXT                           223.8M      317 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                        5.2G      412 \nshared memory                      820K       17 \nunshared pmap                     8512K        5 \n===========                     =======  ======= \nTOTAL                              8.1G     1819 \nTOTAL, minus reserved VM space     7.2G     1819 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000055
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    }
  ]
}
}

Model: MacBookPro18,3, BootROM 8422.121.1, proc 8:6:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Display: ASUS MG28U, 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus), MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Apr  6 2022 05:55:54 version 20.90.45.0.8.7.118 FWID 01-e7138ff2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: USB Optical Mouse
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

### PR DESCRIPTION
**Pull request by Laguna1989**
Should fix #11

### CODE REVIEW

File: impl/game_client_lib/client_network_connection.cpp [hunk 1]
```diff
@@ -30,14 +28,21 @@ ClientNetworkConnection::ClientNetworkConnection(std::string const& ip, std::uin
...
 {
-    m_logger.debug(
-        "ClientNetworkConnection destructor called", { "network", "ClientNetworkConnection" });
-    m_logger.verbose("close socket", { "network", "ClientNetworkConnection" });
-    m_socket->close();
-    m_logger.verbose("stop thread", { "stop thread", "ClientNetworkConnection" });
-    stopThread();
-    m_logger.verbose("reset socket pointer", { "network", "ClientNetworkConnection" });
-    m_socket.reset();
+    try {
```
Comment (Laguna1989) [inline impl/game_client_lib/client_network_connection.cpp:31]: Destructors should never throw

File: impl/game_common_lib/network_helpers.cpp [hunk 2]
```diff
@@ -7,6 +7,9 @@
 void NetworkHelpers::freeSendString(
     std::string const& str, asio::ip::tcp::socket& socket, jt::LoggerInterface& logger)
 {
+    if (!socket.is_open()) {
```
Comment (Laguna1989) [inline impl/game_common_lib/network_helpers.cpp:10]: Just added some safety checks in the free helper functions to avoid reading/writing from closed socket.

File: impl/game_client_lib/client_network_connection.cpp [hunk 3]
```diff
@@ -30,14 +28,21 @@ ClientNetworkConnection::ClientNetworkConnection(std::string const& ip, std::uin
...
+        m_logger.debug(
+            "ClientNetworkConnection destructor called", { "network", "ClientNetworkConnection" });
+
+        m_logger.debug("stop thread", { "stop thread", "ClientNetworkConnection" });
+        stopThread();
```
Comment (Laguna1989) [inline impl/game_client_lib/client_network_connection.cpp:36]: Order in this function was wrong. `stopThread()` needs to be called before closing the socket.

File: impl/game_client_lib/client_network_connection.cpp (hunk 1 above)
Comment (Semitalis) [reply impl/game_client_lib/client_network_connection.cpp:31]: Maybe it's time for some Axivion checks? 😁
